/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as PrototypeRouteImport } from './routes/prototype';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as StorageRouteImport } from './routes/storage';

const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const PrototypeRoute = PrototypeRouteImport.update({
  id: '/prototype',
  path: '/prototype',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/prototype': typeof PrototypeRoute;
  '/settings': typeof SettingsRoute;
  '/storage': typeof StorageRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/prototype': typeof PrototypeRoute;
  '/settings': typeof SettingsRoute;
  '/storage': typeof StorageRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/prototype': typeof PrototypeRoute;
  '/settings': typeof SettingsRoute;
  '/storage': typeof StorageRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/prototype' | '/settings' | '/storage';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/prototype' | '/settings' | '/storage';
  id: '__root__' | '/' | '/prototype' | '/settings' | '/storage';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PrototypeRoute: typeof PrototypeRoute;
  SettingsRoute: typeof SettingsRoute;
  StorageRoute: typeof StorageRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage';
      path: '/storage';
      fullPath: '/storage';
      preLoaderRoute: typeof StorageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/prototype': {
      id: '/prototype';
      path: '/prototype';
      fullPath: '/prototype';
      preLoaderRoute: typeof PrototypeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrototypeRoute: PrototypeRoute,
  SettingsRoute: SettingsRoute,
  StorageRoute: StorageRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
